from .schema import ImageDetailParams


def get_category_tree(params: ImageDetailParams) -> dict[str, dict[str, str | None]]:
    """Get category tree according to industry input."""
    # use default main category and sub category
    target_main_category = ["general"]

    target_category_set = set()

    for industry_name in params.industry:
        industry_name = INDUSTRY_NAME_MAPPING.get(industry_name, industry_name.lower())

        if industry_name in INDUSTRY_CATEGORY_MAPPING:
            for value in INDUSTRY_CATEGORY_MAPPING[industry_name]:
                target_category_set.add(value)

    if len(target_category_set) > 0:
        target_main_category = list(target_category_set)

    category_tree = {}

    for key, value in CATEGORY_DESCRIPTION.items():
        if key in target_main_category:
            category_tree[key] = {}
            for k, v in value.items():
                category_tree[key][k] = v["description"]

    return category_tree


def fix_category(main: str, sub: str) -> tuple[str, str]:
    """Validate main category and sub category output, use default one if they are incorrect."""
    if main not in CATEGORY_DESCRIPTION:
        return [DEFAULT_MAIN_CATEGORY, DEFAULT_SUB_CATEGORY]

    if sub not in CATEGORY_DESCRIPTION[main]:
        return [main, CATEGORY_DESCRIPTION[main].keys()[0]]

    return [main, sub]


def get_description_aspects(main: str, sub: str) -> tuple[str, str, dict[str, str | None]]:
    """Get aspects to be included in the final description with correct category according to input category."""
    main, sub = fix_category(main, sub)

    aspects = CATEGORY_DESCRIPTION[main][sub]["aspects"]

    return main, sub, aspects


DEFAULT_MAIN_CATEGORY = "general"
DEFAULT_SUB_CATEGORY = "general"

# 根据两层级的标签，找到需要描述的字段
# 字段对应的 value 是用于描述这个字段的，如果不需要就设置为 None
CATEGORY_DESCRIPTION = {
    "general": {
        "photography": {
            "description": "Photos from various professional and amateur shoots",
            "aspects": {
                "theme": None,
                "color_scheme": None,
                "mood": None,
                "category": None,
                "usage": None,
                "photo_genre": None,
                "shooting_technique": None,
                "lighting": None,
                "composition": None,
                "lens_choice": None,
                "camera_angle": None,
                "cultural_context": None,
                "tech_specs": None,
                "seasonality": None,
                "holiday_theme": None,
                "environment": None,
                "art_style": None,
            },
        },
        "interface_screenshots": {
            "description": "Screenshots of website or application interface.",
            "aspects": {
                "theme": None,
                "color_scheme": None,
                "interface_type": None,
                "language": None,
                "feature_modules": None,
                "design_style": None,
                "brand_elements": None,
                "industry_domain": None,
                "operating_system": None,
                "device_type": None,
                "screen_size": None,
                "app_type": None,
                "interaction_mode": None,
            },
        },
        "ui/ux_design": {
            "description": "Website or application interfaces, dashboards, icons, etc.",
            "aspects": {
                "theme": None,
                "color_scheme": None,
                "interface_type": None,
                "language": None,
                "feature_modules": None,
                "design_style": None,
                "brand_elements": None,
                "industry_domain": None,
                "operating_system": None,
                "device_type": None,
                "screen_size": None,
                "app_type": None,
                "interaction_mode": None,
            },
        },
        "3d_renders": {
            "description": "Images created with 3D software",
            "aspects": {
                "theme": None,
                "color_scheme": None,
                "mood": None,
                "art_style": None,
                "usage": None,
                "render_type": None,
                "application_field": None,
                "scene_type": None,
                "lighting": None,
                "material_quality": None,
                "perspective": None,
                "dynamic_effects": None,
                "detail_level": None,
                "stylization": None,
                "render_engine": None,
                "post-processing": None,
                "tech_features": None,
                "scene_complexity": None,
            },
        },
        "backgrounds_and_textures": {
            "description": "Various background materials for graphic design",
            "aspects": {
                "theme": None,
                "color_scheme": None,
                "mood": None,
                "category": None,
                "art_style": None,
                "usage": None,
                "repeat_pattern": None,
                "complexity": None,
                "texture_simulation": None,
                "creation_method": None,
                "dimensions": None,
                "dynamic_effects": None,
                "seasonality": None,
                "holiday_theme": None,
                "cultural_style": None,
                "application_scene": None,
            },
        },
        "infographics": {
            "description": "Charts for displaying data and information",
            "aspects": {
                "topic_area": None,
                "chart_type": None,
                "color_scheme": None,
                "data_complexity": None,
                "target_audience": None,
                "design_style": None,
                "data_source": None,
                "usage": None,
                "comparison_type": None,
                "narrative_structure": None,
                "size_format": None,
                "accessibility": None,
                "data_density": None,
                "creation_tool": None,
            },
        },
        "general": {
            "description": "Images not included in other categories",
            "aspects": {
                "usage": "a few phrases describing where this image can be used, e.g., poster design, reference",
                "mood": None,
                "color_scheme": None,
                "cultural_traits": None,
                "industry_domain": None,
                "seasonality": None,
                "holiday_theme": None,
            },
        },
    },
    "game_design": {
        "character_design": {
            "description": None,
            "aspects": {
                "art_style": None,
                "appearance_design": None,
                "color_scheme": None,
                "personality_traits": None,
                "costume_design": None,
                "action_design": None,
                "backstory_elements": None,
                "age_progression": None,
                "facial_expressions": None,
                "proportion_guide": None,
                "ability_visuals": None,
                "detail_design": None,
                "multi_view_display": None,
                "weapon_prop_design": None,
            },
        },
        "environment_design": {
            "description": None,
            "aspects": {
                "art_style": None,
                "mood": None,
                "spatial_layout": None,
                "key_elements": None,
                "color_scheme": None,
                "lighting_effects": None,
                "environmental_narrative": None,
                "natural_elements": None,
                "scale_proportion": None,
                "texture_materials": None,
                "environmental_changes": None,
                "gameplay_integration": None,
                "mood_rendering": None,
                "prop_design": None,
                "perspective_design": None,
            },
        },
        "prop_design": {
            "description": None,
            "aspects": {
                "mood": None,
                "color_scheme": None,
                "functional_design": None,
                "art_style": None,
                "shape_silhouette": None,
                "material_rendering": None,
                "scale": None,
                "dimensions": None,
                "detail_design": None,
                "multi_view_display": None,
                "variant_design": None,
                "historical_background": None,
                "usage_actions": None,
                "special_effects": None,
                "storage_design": None,
            },
        },
        "texture_and_materials": {
            "description": None,
            "aspects": {
                "material_type": None,
                "art_style": None,
                "color_scheme": None,
                "visual_realism": None,
                "style_consistency": None,
                "surface_details": None,
                "light_response": None,
                "performance_optimization": None,
                "environmental_adaptation": None,
                "readability": None,
                "cultural_elements": None,
                "narrative_elements": None,
                "seasonal_changes": None,
            },
        },
        "ui_elements": {
            "description": None,
            "aspects": {
                "information_hierarchy": None,
                "layout_composition": None,
                "usability_intuitiveness": None,
                "consistency": None,
                "interaction_feedback": None,
                "readability": None,
                "aesthetics": None,
                "functionality": None,
                "responsiveness": None,
                "accessibility": None,
                "immersion": None,
                "scalability": None,
                "tutorial_guidance": None,
                "personalization": None,
            },
        },
        "3d_models": {
            "description": None,
            "aspects": {
                "visual_quality": None,
                "realism_stylization": None,
                "topology_structure": None,
                "performance_optimization": None,
                "scale_proportion": None,
                "uv_mapping": None,
                "texture_adaptation": None,
                "skeletal_structure": None,
                "effect_integration": None,
                "environmental_adaptation": None,
                "cultural_elements": None,
            },
        },
    },
    "visual_design": {
        "illustration_and_painting": {
            "description": "Hand-drawn or digital artwork",
            "aspects": {
                "theme": None,
                "art_style": None,
                "color_scheme": None,
                "art_form": None,
                "purpose": None,
                "technique": None,
                "creation_tools": None,
                "cultural_context": None,
                "expression_method": None,
                "creation_period": None,
                "dimensions": None,
                "creation_speed": None,
                "perspective": None,
                "narrative": None,
                "emotion": None,
                "application": None,
                "creation_process": None,
                "target_audience": None,
                "innovation_level": None,
                "texture_rendering": None,
                "composition": None,
                "lighting": None,
            },
        },
        "icons_and_symbols": {
            "description": "Small graphics for interface design and information communication",
            "aspects": {
                "theme": None,
                "art_style": None,
                "color_scheme": None,
                "icon_type": None,
                "complexity": None,
                "application_field": None,
                "dimensions": None,
                "usage": None,
                "cultural_context": None,
                "expression_form": None,
                "design_trend": None,
                "tech_specs": None,
                "readability": None,
                "accessibility": None,
                "semantic_level": None,
                "innovation_level": None,
                "localization": None,
            },
        },
        "brand_identity": {
            "description": "Includes brand manuals, corporate identity systems, etc.",
            "aspects": {
                "color_scheme": None,
                "art_style": None,
                "graphic_elements": None,
                "typography": None,
                "layout_rules": None,
                "brand_voice": None,
                "application_system": None,
                "digital_guidelines": None,
            },
        },
        "vector_graphics": {
            "description": "Scalable graphic design elements",
            "aspects": {
                "art_style": None,
                "theme": None,
                "color_scheme": None,
                "usage": None,
                "complexity": None,
                "cultural_traits": None,
                "industry_type": None,
                "seasonality": None,
                "holiday_theme": None,
                "mood": None,
                "tech_features": None,
                "dimensions": None,
            },
        },
        "logo_and_brand_design": {
            "description": "	Corporate logos, badges, etc.",
            "aspects": {
                "logo_type": None,
                "design_style": None,
                "color_scheme": None,
                "brand_elements": None,
                "industry_domain": None,
                "shape_features": None,
                "brand_personality": None,
                "application": None,
                "cultural_context": None,
                "brand_positioning": None,
                "target_audience": None,
                "brand_history": None,
                "scalability": None,
                "recognition": None,
                "symbolism": None,
                "design_trend": None,
                "brand_story": None,
                "global_adaptation": None,
            },
        },
        "poster_design": {
            "description": None,
            "aspects": {
                "design_type": None,
                "design_theme": None,
                "industry_domain": None,
                "design_style": None,
                "mood": None,
                "visual_elements": None,
                "color_scheme": None,
                "composition": None,
                "layout": None,
                "font_category": None,
                "target_audience": None,
                "creation_medium": None,
                "dimensions": None,
                "design_purpose": None,
                "innovation_level": None,
                "font_type": None,
                "seasonality": None,
                "holiday_theme": None,
                "cultural_style": None,
            },
        },
        "business_card_design": {
            "description": None,
            "aspects": {
                "industry_domain": None,
                "design_style": None,
                "color_scheme": None,
                "visual_elements": None,
                "layout": None,
                "font_category": None,
                "materials_finishes": None,
                "info_elements": None,
                "dimensions": None,
                "cultural_style": None,
                "functional_elements": None,
                "eco_friendly": None,
            },
        },
        "packaging_design": {
            "description": None,
            "aspects": {
                "industry_domain": None,
                "design_style": None,
                "color_scheme": None,
                "visual_elements": None,
                "structure_design": None,
                "material_choice": None,
                "printing_technique": None,
                "text_info": None,
                "functional_elements": None,
                "legal_requirements": None,
                "language_version": None,
                "seasonality": None,
                "holiday_theme": None,
                "eco_friendly": None,
            },
        },
        "social_media_design": {
            "description": "Includes social media images, covers, post templates, etc.",
            "aspects": {
                "theme": None,
                "design_style": None,
                "color_scheme": None,
                "platform_features": None,
                "content_type": None,
                "design_elements": None,
                "layout": None,
                "font_category": None,
                "interactive_elements": None,
                "dimensions": None,
                "seasonality": None,
                "holiday_theme": None,
                "language_version": None,
            },
        },
        "print_design": {
            "description": "Includes magazine layouts, book typography, newspaper ads, etc.",
            "aspects": {
                "color_scheme": None,
                "design_style": None,
                "target_audience": None,
                "page_layout": None,
                "font_category": None,
                "typography": None,
                "design_elements": None,
                "paper_choice": None,
                "printing_technique": None,
                "binding_method": None,
                "cover_design": None,
                "content_structure": None,
                "functional_design": None,
                "brand_consistency": None,
                "print_type": None,
                "tech_specs": None,
            },
        },
    },
    "architecture_and_interior_design": {
        "plan_view": {
            "description": "A bird's-eye view of the space layout",
            "aspects": {
                "space_layout": None,
                "zoning": None,
                "circulation": None,
                "scale": None,
                "dimensions": None,
                "wall_structure": None,
                "furniture_layout": None,
                "building_elements": None,
                "door_window_info": None,
                "elevation_info": None,
                "material_info": None,
                "equipment_systems": None,
                "structural_info": None,
                "orientation": None,
                "legend_notes": None,
                "outdoor_space": None,
                "drawing_info": None,
            },
        },
        "elevation_view": {
            "description": "Shows the facade or interior walls of the building",
            "aspects": {
                "exterior_form": None,
                "height_info": None,
                "color_scheme": None,
                "elevation_layers": None,
                "door_window_layout": None,
                "facade_treatment": None,
                "scale": None,
                "dimensions": None,
                "material_expression": None,
                "decorative_details": None,
                "structural_elements": None,
                "architectural_details": None,
                "terrain_relationship": None,
                "technical_facilities": None,
                "orientation_view": None,
                "notes_annotations": None,
                "drawing_info": None,
                "landscape_elements": None,
            },
        },
        "section_view": {
            "description": "Displays a vertical cross-section of the building or interior space",
            "aspects": {
                "height_info": None,
                "scale": None,
                "dimensions": None,
                "vertical_relationships": None,
                "structural_system": None,
                "wall_construction": None,
                "stairs_elevators": None,
                "door_window_info": None,
                "terrain_relationship": None,
                "roof_design": None,
                "interior_design": None,
                "equipment_systems": None,
                "section_indicator": None,
                "material_labels": None,
                "underground_structure": None,
                "elevation_info": None,
                "landscape_elements": None,
                "notes_annotations": None,
                "drawing_info": None,
            },
        },
        "3d_model_view": {
            "description": "Used to show the three-dimensional structure of the building or interior space",
            "aspects": {
                "spatial_layout": None,
                "atmosphere_creation": None,
                "color_scheme": None,
                "lighting_effects": None,
                "form_volume": None,
                "material_texture": None,
                "detail_rendering": None,
                "environmental_integration": None,
                "view_selection": None,
                "function_display": None,
                "structural_expression": None,
                "circulation_flow": None,
                "scale_reference": None,
                "time_dimension": None,
                "material_performance": None,
                "system_integration": None,
                "sustainability_features": None,
                "signage_system": None,
            },
        },
        "render_view": {
            "description": "A realistic image generated from a 3D model to showcase the final design effect",
            "aspects": {
                "lighting_effects": None,
                "material_texture": None,
                "color_scheme": None,
                "spatial_proportion": None,
                "environmental_integration": None,
                "atmosphere_creation": None,
                "detail_display": None,
                "perspective_choice": None,
                "functional_hints": None,
                "scene_arrangement": None,
                "seasonal_expression": None,
                "realism_balance": None,
                "material_performance": None,
                "tech_implications": None,
                "composition_focus": None,
                "rendering_techniques": None,
            },
        },
        "construction_drawing": {
            "description": "Contains detailed technical information for guiding construction",
            "aspects": {
                "floor_plan": None,
                "precise_dimensions": None,
                "structural_details": None,
                "material_specifications": None,
                "construction_details": None,
                "system_diagrams": None,
                "detail_drawings": None,
                "door_schedule": None,
                "drawing_index": None,
                "elevation_sections": None,
                "drawing_scale": None,
                "revision_notes": None,
                "construction_sequence": None,
                "fire_compartments": None,
            },
        },
        "conceptual_sketches": {
            "description": "Showcases initial design concepts and ideas",
            "aspects": {
                "spatial_concept": None,
                "mood": None,
                "functional_flow": None,
                "design_expression": None,
                "proportions": None,
                "form_exploration": None,
                "landscape_elements": None,
                "environmental_integration": None,
                "structural_concept": None,
                "lighting_consideration": None,
                "material_hints": None,
                "sustainability": None,
                "cultural_elements": None,
                "innovation_hints": None,
                "annotations": None,
                "sketch_technique": None,
            },
        },
        "landscape_design": {
            "description": "Planning of outdoor spaces around the building",
            "aspects": {
                "master_plan": None,
                "functional_zoning": None,
                "plant_selection": None,
                "landscape_elements": None,
                "water_features": None,
                "hardscape_design": None,
                "terrain_design": None,
                "view_analysis": None,
                "ecological_design": None,
                "lighting_design": None,
                "signage_system": None,
                "microclimate_control": None,
                "material_specs": None,
                "drainage_design": None,
                "construction_details": None,
                "maintenance_plan": None,
                "seasonal_design": None,
                "cultural_integration": None,
            },
        },
        "detail_design": {
            "description": "Focuses on specific design details such as doors, windows, stairs, railings, etc",
            "aspects": {
                "construction_details": None,
                "precise_dimensions": None,
                "installation_guide": None,
                "material_specs": None,
                "joint_design": None,
                "waterproofing": None,
                "load_bearing": None,
                "thermal_design": None,
                "fire_protection": None,
                "equipment_integration": None,
                "aesthetic_details": None,
                "acoustic_treatment": None,
                "durability": None,
                "maintainability": None,
                "eco_friendliness": None,
                "standard_references": None,
                "testing_standards": None,
                "legend_notes": None,
            },
        },
        "material_boards": {
            "description": "Displays the materials, colors, and textures used in the design",
            "aspects": {
                "material_samples": None,
                "color_scheme": None,
                "texture_feel": None,
                "material_specs": None,
                "application_areas": None,
                "performance": None,
                "material_combinations": None,
                "light_effects": None,
                "sustainability_info": None,
                "maintenance_guide": None,
                "brand_supplier": None,
                "cost_info": None,
                "installation_method": None,
                "scale": None,
                "dimensions": None,
                "time_considerations": None,
                "customization_options": None,
                "related_elements": None,
                "alternatives": None,
            },
        },
    },
    "furniture_and_equipment": {
        "general": {
            "description": None,
            "aspects": {
                "overall_appearance": None,
                "design_style": None,
                "color_scheme": None,
                "material_showcase": None,
                "function_demonstration": None,
                "usage_scenarios": None,
                "detail_close-ups": None,
                "comfort_demonstration": None,
                "color_variations": None,
                "weight_capacity": None,
                "dimension_information": None,
                "structure_explanation": None,
                "environmental_certification": None,
            },
        }
    },
}

INDUSTRY_NAME_MAPPING = {
    "室内设计": "interior design",
    "建筑设计": "architecture design",
    "服装设计": "fashion design",
    "插画设计": "illustration",
    "视觉设计": "graphic design",
    "UI/UX 设计": "ui/ux",
    "3D 设计": "3d",
    "游戏设计": "game design",
    "自媒体运营": "social media",
    "摄影": "photography",
    "电商": "e-commerce",
    "互联网": "internet",
    "其他": "others",
}


INDUSTRY_CATEGORY_MAPPING = {
    "interior design": [
        "general",
        "architecture_and_interior_design",
        "furniture_and_equipment",
    ],
    "architecture design": ["general", "architecture_and_interior_design"],
    "illustration": ["general", "visual_design"],
    "graphic design": ["general", "visual_design"],
    "ui/ux": ["general"],
    "3d": ["general", "game_design"],
    "game design": ["general", "game_design"],
    "social media": ["general", "visual_design"],
    "photography": ["general"],
    "e-commerce": ["general"],
    "internet": ["general"],
    "fashion design": ["general"],
    "others": ["general"],
}
